'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class TC0013
    Public Property cbnumi As Integer
    Public Property cbtccanumi As Nullable(Of Integer)
    Public Property cbtccanumi1 As Nullable(Of Integer)
    Public Property cbcant As Nullable(Of Integer)

End Class
