
'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic


Partial Public Class TD001

    Public Property danumi As Integer

    Public Property dacanumi As Nullable(Of Integer)

    Public Property dacant1 As Nullable(Of Integer)

    Public Property dacant2 As Nullable(Of Integer)

    Public Property dapreciou As Nullable(Of Decimal)

    Public Property dafinicio As Nullable(Of Date)

    Public Property daffin As Nullable(Of Date)

    Public Property daestado As Nullable(Of Integer)

    Public Property dafact As Nullable(Of Date)

    Public Property dahact As String

    Public Property dauact As String


End Class
