
'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic


Partial Public Class TI0052

    Public Property iiid As Integer

    Public Property iiigid As Nullable(Of Integer)

    Public Property iicodpro As Nullable(Of Integer)

    Public Property iicant As Nullable(Of Integer)

    Public Property iitotcant As Nullable(Of Integer)

    Public Property iipcosto As Nullable(Of Decimal)

    Public Property iifact As Nullable(Of Date)

    Public Property iihact As String

    Public Property iiuact As String


End Class
