
'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic


Partial Public Class TI0051

    Public Property ihid As Integer

    Public Property ihigid As Nullable(Of Integer)

    Public Property ihcodpro As Nullable(Of Integer)

    Public Property ihcant As Nullable(Of Integer)

    Public Property ihtotcant As Nullable(Of Integer)

    Public Property ihpcosto As Nullable(Of Decimal)

    Public Property ihfact As Nullable(Of Date)

    Public Property ihhact As String

    Public Property ihuact As String


End Class
