'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class TI005
    Public Property igid As Integer
    Public Property igfdoc As Nullable(Of Date)
    Public Property igobs As String
    Public Property igcodpack As Nullable(Of Integer)
    Public Property igcantP As Nullable(Of Integer)
    Public Property igpcosto As Nullable(Of Decimal)
    Public Property igcantNP As Nullable(Of Integer)
    Public Property igfechaNP As Nullable(Of Date)
    Public Property igest As Nullable(Of Integer)
    Public Property igalm As Nullable(Of Integer)
    Public Property igfact As Nullable(Of Date)
    Public Property ighact As String
    Public Property iguact As String

End Class
