
'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic


Partial Public Class TO005

    Public Property olnumi As Integer

    Public Property olnumichof As Nullable(Of Integer)

    Public Property olnumiconci As Nullable(Of Integer)

    Public Property olfecha As Nullable(Of Date)

    Public Property olmrec As Nullable(Of Decimal)

    Public Property olfact As Nullable(Of Date)

    Public Property olhact As String

    Public Property oluact As String

    Public Property olCredito As Nullable(Of Decimal)

    Public Property olTipoCambio As Nullable(Of Decimal)

    Public Property olEstado As Nullable(Of Integer)



    Public Overridable Property TO0051 As ICollection(Of TO0051) = New HashSet(Of TO0051)

    Public Overridable Property TO0052 As ICollection(Of TO0052) = New HashSet(Of TO0052)


End Class
