'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class TO001D
    Public Property oadnumi As Integer
    Public Property oadoanumi As Integer
    Public Property oadestado As Integer
    Public Property oaddescrip As String
    Public Property oadcampo1 As Nullable(Of Integer)
    Public Property oadcampo2 As Nullable(Of Decimal)
    Public Property oadcampo3 As String
    Public Property oadfecha As Nullable(Of Date)
    Public Property oadusuario As String
    Public Property oadhora As String

End Class
