'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class TO0051
    Public Property omnumi As Integer
    Public Property omolnumi As Integer
    Public Property omestado As Integer
    Public Property omTipoCam As Decimal
    Public Property omCorteD As Decimal
    Public Property omCantD As Decimal
    Public Property omTotalD As Decimal
    Public Property omCorteB As Decimal
    Public Property omCantB As Decimal
    Public Property omTotalB As Decimal

    Public Overridable Property TO005 As TO005

End Class
