'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class TO0052
    Public Property onnumi As Integer
    Public Property onolnumi As Integer
    Public Property onestado As Integer
    Public Property onBanco As String
    Public Property onMoneda As String
    Public Property onNDepos As String
    Public Property onFecha As Date
    Public Property onMonto As Decimal

    Public Overridable Property TO005 As TO005

End Class
