
'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic


Partial Public Class V_StockDisp

    Public Property iacprod As Nullable(Of Integer)

    Public Property iacant As Nullable(Of Decimal)

    Public Property Pedidos As Decimal

    Public Property Disponible As Nullable(Of Decimal)

    Public Property iaalm As Nullable(Of Integer)


End Class
