
'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic


Partial Public Class v_VentasDetalleDespacho

    Public Property oanumi As Integer

    Public Property oafdoc As Nullable(Of Date)

    Public Property oaccli As Nullable(Of Integer)

    Public Property ccdesc As String

    Public Property oarepa As Nullable(Of Integer)

    Public Property oaest As Nullable(Of Integer)

    Public Property oaap As Nullable(Of Integer)

    Public Property obcprod As String

    Public Property cadesc As String

    Public Property cauventa As Nullable(Of Integer)

    Public Property cedesc As String

    Public Property obpbase As Nullable(Of Decimal)

    Public Property obpcant As Nullable(Of Decimal)

    Public Property obptot As Nullable(Of Decimal)

    Public Property obdesc As Nullable(Of Decimal)

    Public Property obtotal As Nullable(Of Decimal)

    Public Property oaccbnumi As Integer

    Public Property cbdesc As String

    Public Property cacod As String


End Class
