
'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic


Partial Public Class VR_CajaDetalle

    Public Property oanumi As Integer

    Public Property oafdoc As Nullable(Of Date)

    Public Property oacnrofac As Nullable(Of Long)

    Public Property cliente As String

    Public Property oarepa As Nullable(Of Integer)

    Public Property oaest As Nullable(Of Integer)

    Public Property oaap As Nullable(Of Integer)

    Public Property oapg As Nullable(Of Integer)

    Public Property total As Nullable(Of Decimal)

    Public Property contado As Nullable(Of Decimal)

    Public Property credito As Decimal

    Public Property tcre As Integer

    Public Property estado As Integer


End Class
