'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class VR_GO_DespachoXProducto
    Public Property oaccbnumi As Integer
    Public Property canumi As Integer
    Public Property cacod As String
    Public Property cadesc As String
    Public Property cadesc2 As String
    Public Property categoria As String
    Public Property obpcant As Nullable(Of Decimal)
    Public Property oacnconc As Nullable(Of Integer)
    Public Property oaest As Nullable(Of Integer)
    Public Property oaap As Nullable(Of Integer)
    Public Property oafdoc As Nullable(Of Date)
    Public Property caja As Nullable(Of Decimal)
    Public Property Unidad As Nullable(Of Decimal)
    Public Property Total As Nullable(Of Decimal)
    Public Property caconv As Nullable(Of Decimal)

End Class
